version: 0.1
log:
  level: info

auth:
  yt:
    cluster: hume

storage:
    yt:
        cluster: hume
        home_directory: //sys/admin/registry

middleware:
  repository:
    - name: yt
      options:
        cluster: hume
        home_directory: //sys/admin/registry
http:
    addr: :5000
